config/routes.rb
Rails.application.routes.draw do
  resources :listings
  resources :reservations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/listings/:id/toggle_date/:y/:m/:d', to: 'listings#toggle_date', as: 'listing_toggle_date'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ApplicationRecord
  serialize :dates_blocked, Array

  has_many :reservations
  has_one :reservation_dates_blocked
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :listing

  def start_time
    start_date
  end

  def end_time
    end_date
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy, :toggle_date]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_date
    date = Date.new(params[:y].to_i, params[:m].to_i, params[:d].to_i)
    
    if @listing.dates_blocked.include?(date)
      @listing.dates_blocked.delete(date)
      notice = 'Date has been unblocked'
    else
      @listing.dates_blocked << date
      notice = 'Date has been blocked'
    end
    @listing.dates_blocked.sort
    @listing.save

    redirect_to @listing, notice: notice
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name)
    end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:name, :start_date, :end_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleCalendarSetup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_for(listing) do |f| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= listing.name %></td>
        <td><%= link_to 'Show', listing %></td>
        <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
        <td><%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<style>
  .day {
      text-align: center;
      vertical-align: middle;
      border-style: solid;
      border-color: #000;
      border-width: 1px;
      color: #000;
    }

    .wday-0 {}
    .wday-1 {}
    .wday-2 {}
    .wday-3 {}
    .wday-4 {}
    .wday-5 {}
    .wday-6 {}

    .today {}
    .past {}
    .future {}

    .start-date {}

    .prev-month {
      visibility: hidden;
    }
    .next-month {
      visibility: hidden;
    }
    .current-month {}

    .has-events {
      font-weight: bolder;
    }

    .is-blocked {
      color: #ff0000;
      font-weight: bolder;
    }

    .toggle-blocked-date {
      text-decoration: none;
    }
</style>

<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @listing.name %>
</p>

<% (0..2).each do |mo_offset| %>
  <%= month_calendar(start_date: (Date.today.beginning_of_month + mo_offset.months), events: @listing.reservations) do |date, reservations| %>
    <% if date < Date.today %>
      <%= date.day %>
    <% else %>
      <% if reservations.count.positive? %>
        X
      <% else %>
        <%= link_to (@listing.dates_blocked.include?(date) ? 'X' : date.day), listing_toggle_date_path(@listing, date.year, date.month, date.day), remote: true, class: "toggle-blocked-date#{@listing.dates_blocked.include?(date) ? ' is-blocked' : nil}", 'data-day': date.day %>
      <% end %>
    <% end %>
  <% end %>
<% end %>


<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

<script>
  $(document).ready(function() {
    $(".toggle-blocked-date").on("ajax:success", function(e, data, status, xhr) {
      var el = e.target;
      if($(el).hasClass('is-blocked')) {
        $(el).html($(el).attr('data-day'));
        $(el).removeClass('is-blocked');
      } else {
        $(el).html('X');
        $(el).addClass('is-blocked');
      }
    }).on("ajax:error", function(e, xhr, status, error) {
      console.log("ERROR:", error);
    });
  });
</script>

app/views/reservations/_form.html.erb
<%= form_for(reservation) do |f| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% reservation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :start_date %>
    <%= f.date_select :start_date %>
  </div>

  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_select :end_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td><%= reservation.name %></td>
        <td><%= reservation.start_date %></td>
        <td><%= reservation.end_date %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reservation.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @reservation.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @reservation.end_date %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>